repository:
  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY

# Does not currently work. Import the ruleset manually.
# rulesets:
#   - name: default-ruleset
#     target: branch
#     enforcement: active
#     conditions:
#       ref_name:
#         include:
#           - "~DEFAULT_BRANCH"
#           - "refs/heads/releases/*"
#         exclude: []
#     rules:
#       - type: pull_request
#         parameters:
#           required_approving_review_count: 1
#           require_code_owner_review: true

#     bypass_actors:
#       - actor_id: 5
#         actor_type: RepositoryRole
#         bypass_mode: always